let datos = [
	{
        id: 1,
        image: 'productsimg/egg.webp',
        name: 'Huevo',
        locale : 'Tienda de la esquina xd',
        description: 'Es un huevo... ta bien caro',
        price: 0.600,
    },
    {
        id: 2,
        image: 'productsimg/chanclas.webp',
        name: 'Chanclas',
        locale : 'frescatommy o como se llame',
        description: 'Unas chanclas bien perronas pa atraer hembras',
        price: 20.000,
    },
    {
        id: 3,
        image: 'productsimg/sugar.webp',
        name: '1/2 lb de azucar',
        locale : 'Tienda de la esquina',
        description: 'Media libra de azucar',
        price: 1.600,
    },
    {
        id: 4,
        image: 'productsimg/catbread.webp',
        name: '2k de pan',
        locale : 'En una panaderia',
        description: 'Viene con 5 panes, un pan para cada dia',
        price: 2.000,
    },
    {
        id: 5,
        image: 'productsimg/rice.webp',
        name: '1/2 lb de arroz',
        locale : 'En la tienda de la esquina otra vez',
        description: 'Eres un arroz pero al reves',
        price: 1.200,
    },
    {
        id: 6,
        image: 'productsimg/cebolla.jpg',
        name: 'Cebolla',
        locale : 'Tienda',
        description: 'UNA CEBOLLA',
        price: 1.000,
    },
    ]